[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
for = "/service-worker.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/page-data/*"

[headers.values]
Cache-Control = "no-cache, must-revalidate"
